---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-2
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-2
subjects:
- kind: ServiceAccount
  name: external-dns-2
  namespace: externaldns2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-2
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-2
  template:
    metadata:
      labels:
        app: external-dns-2
    spec:
      serviceAccountName: external-dns-2
      containers:
      - name: external-dns-2
        image: gcr.io/harness-test-338118/external-dns:latest
        # If authentication is disabled and/or you didn't create
        # a secret, you can remove this block.
        envFrom:
        - secretRef:
            # Change this if you gave the secret a different name
            name: pihole-password
        args:
        - --source=service
        - --source=ingress
        # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
        # You don't need to set this flag, but if you leave it unset, you will receive warning
        # logs when ExternalDNS attempts to create TXT records.
        - --registry=noop
        # IMPORTANT: If you have records that you manage manually in Pi-hole, set
        # the policy to upsert-only so they do not get deleted.
        - --policy=upsert-only
        - --provider=pihole
        # Change this to the actual address of your Pi-hole web server
        - --pihole-server=http://192.168.1.3
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
