apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-vol
        ports:
        - containerPort: 80
      volumes:
        - name: nginx-vol
          persistentVolumeClaim:
            claimName: nginx-pvc
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.lab.lucid3.org
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs-csi-api"
spec:
  storageClassName: truenas-nfs-csi-api
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
