kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs-api
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs-csi-api"
spec:
  storageClassName: truenas-nfs-csi-api
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

